### ISSUE TITLE
Kompilierung auf eigener Maschine testen

### ISSUE THREAD

**Issue by Rookfighter** [AvS2016/ParallelTSP#13]
- jeder sollte die Abhängikeiteninstallation und die Kompilierung bei sich durchführen können
- bei Rückfragen gerne bei mir melden
  - aber bitte auch selbst nach funktionsweisen wie CMake und Shell scripting schauen
  - wenn etwas nicht funktioniert auch in die scripte schauen -> ich habe eure Installationsumgebung nicht, kann also auch nur begrenzt eure probleme selbst testen

**Comment by TimoCode** [comment]
läuft bei mir
