### ISSUE TITLE
Einarbeitung in Git

### ISSUE THREAD

**Issue by Rookfighter** [AvS2016/ParallelTSP#17]
- mit git vertraut machen
  - branches, push, pull, commit, staging, checkout, tags, revision, rebase, merge, merge conflicts
- ein paar gute blog einträge mit best practices
  - http://chris.beams.io/posts/git-commit/
  - http://blog.8thlight.com/makis-otman/2015/07/08/git-disciplined.html
  - https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by Rookfighter** [comment]
@TimoCode 
@ViktorProjekte 
bitte auch machen

**Comment by JoramM** [comment]
läuft denk ich, oder?
