### ISSUE TITLE
SSH Konfiguration anfragen

### ISSUE THREAD

**Issue by Rookfighter** [AvS2016/ParallelTSP#18]
- bei Pascal (oder wer auch immer den Rechnerpool verwaltet) wegen SSH Freigabe/Konfiguration anfragen
- SSH konfiguration erlaubt kein anmelden von anderen MACs
  - es ist kein Problem mit Ports oder Firewall, sondern eine Konfiguration des SSH Daemon!

**Comment by JoramM** [comment]
Pascal hab ich angeschrieben - warte auf ne Rückmeldung.

**Comment by Rookfighter** [comment]
Haben die ersten OSX Maschinen konfiguriert. Pascal gibt uns einfach root rechte.
