### ISSUE TITLE
Gedanken vom 19.04 erfassen

### ISSUE THREAD

**Issue by Rookfighter** [AvS2016/ParallelTSP#6]
Anforderungen:
- Gedanken, Beschlüsse, Meinungen zusammenfassen
  - Meinung von Prof zu Technologien erfassen
- bevorzugt als Markdown Datei (für Leute ohne MS Office)
  - siehe als Beispiel **doc/Technologies.md**
- Entscheidung über Notizdateinamen Schema
  - z.B. "YYYY_MM_DD.md"

**Comment by TimoCode** [comment]
Siehe: https://github.com/AvS2016/ParallelTSP/blob/master/doc/Projektkontext.md
