### ISSUE TITLE
Visualisierung des Beispiel Graphen

### ISSUE THREAD

**Issue by Rookfighter** [AvS2016/ParallelTSP#9]
- Skript oder Executeable erstellen
- soll JSON Datei (unser format) lesen und SVG ausgeben
- Technologie auswählen
  - siehe https://github.com/AvS2016/ParallelTSP/blob/master/doc/Visualisation.md
- Aussehen evtl. mit Raster, um Knoten leichter zu identifizieren
  - siehe Bilder in http://www.theprojectspot.com/tutorial-post/applying-a-genetic-algorithm-to-the-travelling-salesman-problem/5
- Beispiel Graph in https://github.com/AvS2016/ParallelTSP/tree/master/graph

**Comment by Rookfighter** [comment]
@JoramM 
Wir haben am Dienstag gar nicht darüber gesprochen. Wie weit bist du da? Kannst du uns hier kurz ein Update reinschreiben? Evt. auch Probleme, die du vllt entdeckt hast.

**Comment by Rookfighter** [comment]
Bitte bis spätestens 19:00Uhr am 21.05. fertigstellen. Ob eine Bibliothek oder Nur Commandline befehle verwendet werden um GNUplot zu verwenden ist nicht wichtig.
Bitte auch den Branch von Master rebasen und den PathSerializer verwenden, anstatt die json bibliothek. Das Rebasen wird zu Konflikten führen. Falls du bei der Auflösung der Konflikte unsicher bist kannst du mich gerne fragen.

**Comment by JoramM** [comment]
Es seht nur noch das Hinzufügen der Gnuplot-Abhängigkeit aus.
